- name: Ensure the /letsencrypt directory exists
  ansible.builtin.file:
    path: /letsencrypt
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Ensure acme.json exists and set permissions
  ansible.builtin.file:
    path: /letsencrypt/acme.json
    state: touch
    owner: root
    group: root
    mode: '0600'
